name: pciutils
version: 1.1
vendor: David Chen <david.chen@canonical.com>
summary: PCI Utilities
description: PCI Tools for Snappy devices
icon: icon.png
binaries:
   lspci: 
     exec: usr/local/sbin/lspci
     security-policy:
       apparmor: security/apparmor.profile
       seccomp:  security/seccomp.filter           
parts:
    tools:
        plugin: x-custom
        source: https://github.com/gittup/pciutils.git
        source-type: git
        custom-cmds: ../../../build-lspci.sh $SNAPCRAFT_PART_INSTALL_DIR

